extraPorts:
  - name: beats
    containerPort: 5044

persistence:
  enabled: true

logstashConfig:
  logstash.yml: |
    http.host: 0.0.0.0
    xpack.monitoring.enabled: false

logstashPipeline:
  logstash.conf: |
    input { beats { port => 5044 }}
    output { stdout { codec => rubydebug } elasticsearch { hosts => ["http://elasticsearch-master:9200"] index => "logstash" } }